# base configuration
train_bc: 1
eval_bc: 8
num_epochs: 8000
data_path: './visible_test'
eval_path: './visible_test'
data_aug: True 
val_length: 8000

# train process configuration
val_inter:  50
save_inter: 100

# model configuration
in_channels: 3
out_channels: 3
block_out_channels: [
    128,
    256,
    512,
    512
  ]
down_block_types: [
    "DownEncoderBlock2D",
    "DownEncoderBlock2D",
    "DownEncoderBlock2D",
    "DownEncoderBlock2D"
  ]
up_block_types: [
    "UpDecoderBlock2D",
    "UpDecoderBlock2D",
    "UpDecoderBlock2D",
    "UpDecoderBlock2D"
  ]
latent_channels: 4
layers_per_block: 2
sample_size: 512
resume_path: 'weights/exp_2_25/input_save'
resume_path_con: 'weights/exp_2_25/output_save'
dis_path: 'weights/exp_2_25/dis_save/discriminator.pt'

# accelerate config
split_batches: False
mixed_precision: 'fp16'
log_with: 'tensorboard'
project_dir: 'weights/exp_2_26'
gradient_accumulation_steps: 1